on:
  push:
    paths:
      - "**.json"
      - "**.js"
      - "**.jsx"
      - "**.mjs"
      - "**.ts"
      - "**.tsx"
      - "**.lockb"
      - ".github/workflows/test.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22
      - name: install dependencies
        run: bun install
      - name: stub generated
        run: |
          mkdir -p site/src/generated/killed-in-gaza
          echo '{"pageCount": 0}' > site/src/generated/killed-in-gaza/page-info.json
      - name: run typechecks
        run: bun run types
